#  https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    app: fluentd
    version: v1
spec:
  selector:
    matchLabels:
      app: fluentd
      version: v1
  template:
    metadata:
      labels:
        app: fluentd
        version: v1
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: hands-on/fluentd:v1
          env:
            # specifies the hostname of the Elasticsearch service
            - name: FLUENT_ELASTICSEARCH_HOST
              # Since the Fluentd Pod runs in a different namespace to Elasticsearch, the hostname cannot be
              # specified using its short name, that is, elasticsearch. Instead, the namespace part of the DNS
              # name must also be specified, that is, elasticsearch.logging. As an alternative, the fully qualified
              # domain name (FQDN), elasticsearch.logging.svc.cluster.local, can also be used. But since the last
              # part of the DNS name, svc.cluster.local, is shared by all DNS names inside a Kubernetes cluster,
              # it does not need to be specified.
              value: 'elasticsearch.logging'
              # specifies the port that’s used to communicate with Elasticsearch
            - name: FLUENT_ELASTICSEARCH_PORT
              value: '9200'
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: 'http'
            - name: FLUENT_ELASTICSEARCH_SED_DISABLE
              value: 'true'
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: journal
              mountPath: /var/log/journal
              readOnly: true
            - name: fluentd-extra-config
              mountPath: /fluentd/etc/conf.d
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: journal
          hostPath:
            path: /run/log/journal
        - name: fluentd-extra-config
          configMap:
            name: 'fluentd-hands-on-config'
      terminationGracePeriodSeconds: 30
#
#
# - Three folders on the host (that is, the Node) are mapped to the Fluentd Pod. These folders contain the
# log files that Fluentd will tail and collect log records from. The folders are /var/log,
# /var/lib/docker/containers, and /run/log/journal.
# - Our own configuration file, which specifies how Fluentd will process log records from
# our microservices, is mapped using a ConfigMap called fluentd-hands-on-config to
# the /fluentd/etc/conf.d folder. The base Docker image configures Fluentd to include
# any configuration file that’s found in the /fluentd/etc/conf.d folder.
