spring.config.import: "configserver:"

spring:
  application.name: product-composite
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD}

# 1- Connect to the config server using the http://localhost:8888 URL when it runs outside
#   Docker, and using the http://config-server:8888 URL when running in a Docker container
# 2- Use HTTP Basic authentication, based on the value of the CONFIG_SERVER_USR and CONFIG_
#   SERVER_PWD properties, as the client’s username and password
# 3- Try to reconnect to the config server during startup up to 20 times, if required 
# 4- If the connection attempt fails, the client will initially wait for 3 seconds before 
#   trying to reconnect
# 4- The wait time for subsequent retries will increase by a factor of 1.3
# 5- The maximum wait time between connection attempts will be 10 seconds
# 6- If the client can’t connect to the config server after 20 attempts, its startup will fail

---
spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://config-server:8888