# To support canary tests, a routing rule is required in the virtual services that always routes
#  the canary testers to the new subset. To identify canary testers, we will assume that requests 
# from a canary tester contain an HTTP header named X-group with the value test.
{{- define "common.istio_vs_green_blue_deploy" -}}
{{- range $name := .Values.virtualServices }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $name }}
spec:
# used to specify the names of the Kubernetes service that this VirtualService will apply to
  hosts:
  - {{ $name }}
  http:
  - match:
# One route matching the canary testers’ HTTP header, X-group, set to test. This route
# always sends the requests to the new subset.
    - headers:
        X-group:
          exact: test
    route:
    - destination:
        host: {{ $name }}
        subset: new
  - route:
    - destination:
        host: {{ $name }}
        subset: old
# The weight is specified as a percentage and the sum of the weights will always be 100
      weight: 100
    - destination:
        host: {{ $name }}
        subset: new
      weight: 0
---
{{- end -}}
{{- end -}}
